### ISSUE TITLE
Better spacing could be made in landing page content

### ISSUE THREAD

**Issue by MohitNamdev22** [itshypon/PixelCrypt#10]
![image](https://github.com/itshypon/PixelCrypt/assets/89779447/3ed987cf-72d7-4d0c-877b-bea39ba55f96)

**Comment by itshypon** [comment]
@MohitNamdev22 Would you like work on it and share screenshot of better spacing?

**Comment by MohitNamdev22** [comment]
Yes I want to work on it under Hacktoberfest 2023

after making changes it would look like 
![image](https://github.com/itshypon/PixelCrypt/assets/89779447/965fbc9d-b414-4eca-bc0d-74385b07db8e)

**Comment by itshypon** [comment]
@MohitNamdev22 Personally, I like the old look. Although, one guy is already working on UI part so I'll wait for his changes also.
